import { createContext, useContext, useState, useMemo } from 'react'

const translations = {
  fr: {
    appName: 'UQO Requests',
    appTagline: 'Plateforme de gestion des demandes universitaires',
    nav: {
      dashboard: 'Tableau de bord', newRequest: 'Nouvelle demande',
      notifications: 'Notifications', myRequests: 'Mes demandes',
      allRequests: 'Toutes les demandes', logout: 'Se déconnecter',
      login: 'Se connecter', register: "S'inscrire", home: 'Accueil',
    },
    home: {
      heroTitle: 'Gérez vos demandes universitaires',
      heroSubtitle: 'Une plateforme moderne, sécurisée et intuitive pour soumettre, suivre et résoudre vos requêtes administratives — le tout depuis un seul espace centralisé.',
      heroCtaPrimary: 'Créer une demande', heroCtaSecondary: 'Se connecter',
      heroCta: 'Accéder au tableau de bord',
      stat1: 'Demandes traitées', stat2: 'Délai moyen', stat3: 'Taux de résolution',
      stat1Val: '1 200+', stat2Val: '24h', stat3Val: '98%',
      feature1Title: 'Suivi en temps réel', feature1Desc: "Suivez l'avancement de vos demandes à chaque étape du processus.",
      feature2Title: 'Communication directe', feature2Desc: 'Échangez directement avec les gestionnaires via la messagerie intégrée.',
      feature3Title: 'Notifications instantanées', feature3Desc: 'Soyez alerté immédiatement lors de chaque mise à jour.',
      feature4Title: 'Sécurité renforcée', feature4Desc: 'Authentification à deux facteurs pour protéger votre compte.',
      welcomeBack: 'Bon retour,',
      ctaTitle: 'Prêt à commencer ?',
      ctaSubtitle: "Rejoignez les étudiants de l'UQO qui utilisent déjà la plateforme.",
      ctaBtn: 'Créer mon compte',
      howItWorks: 'Comment ça fonctionne',
      step1Title: 'Soumettez', step1Desc: 'Remplissez le formulaire de demande en quelques clics.',
      step2Title: 'Suivez', step2Desc: 'Consultez le statut et les mises à jour de votre demande.',
      step3Title: 'Communiquez', step3Desc: "Échangez avec votre gestionnaire jusqu'à la résolution.",
    },
    auth: {
      loginTitle: 'Connexion', loginSubtitle: 'Accédez à votre espace personnel',
      registerTitle: 'Créer un compte', registerSubtitle: 'Rejoignez la communauté UQO',
      emailLabel: 'Adresse email', emailPlaceholder: 'jean.dupont@uqo.ca',
      passwordLabel: 'Mot de passe', passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirmer le mot de passe',
      fullNameLabel: 'Nom complet', fullNamePlaceholder: 'Jean Dupont',
      codeLabel: 'Code de vérification', codePlaceholder: '123456',
      codeInfo: 'Un code à 6 chiffres a été envoyé à votre adresse email. Ce code est valide 15 minutes.',
      next: 'Continuer', back: 'Retour', submit: 'Se connecter',
      submitRegister: "S'inscrire", verify: 'Vérifier le code',
      forgotPassword: 'Mot de passe oublié ?',
      noAccount: 'Pas encore de compte ?', hasAccount: 'Déjà un compte ?',
      signUp: "S'inscrire", signIn: 'Se connecter',
      passwordHint: 'Minimum 8 caractères, 1 majuscule, 1 chiffre',
      show: 'Afficher', hide: 'Masquer',
      step1: 'Email', step2: 'Mot de passe', step3: 'Vérification',
      leftTitle: "La plateforme de référence pour les étudiants UQO",
      leftSubtitle: 'Simple, rapide et sécurisé.',
      leftPoint1: 'Soumettez vos demandes en quelques clics',
      leftPoint2: 'Suivez leur progression en temps réel',
      leftPoint3: 'Communiquez directement avec les gestionnaires',
    },
    dashboard: {
      title: 'Tableau de bord', managerTitle: 'Gestion des demandes',
      subtitle: 'Voici ce qui se passe sur votre espace',
      managerSubtitle: "Vue d'ensemble de toutes les demandes",
      newRequest: 'Nouvelle demande',
      total: 'Total', submitted: 'Soumis', inProgress: 'En cours',
      resolved: 'Résolu', closed: 'Fermé', all: 'Toutes',
      loading: 'Chargement...', error: 'Impossible de charger les données.',
      colTitle: 'Titre', colCategory: 'Catégorie', colStatus: 'Statut',
      colDate: 'Date', colCreatedBy: 'Créé par',
      statusChart: 'Répartition par statut',
      recentRequests: 'Demandes récentes', recentActivity: 'Activité récente',
      recentNotifications: 'Notifications récentes',
      viewAll: 'Voir tout', noActivity: 'Aucune activité récente',
      noRecentRequests: 'Aucune demande pour le moment',
      goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir',
    },
    myRequests: {
      title: 'Mes demandes', managerTitle: 'Toutes les demandes',
      subtitle: 'Gérez et suivez vos demandes', managerSubtitle: 'Supervisez et traitez toutes les demandes',
      newRequest: 'Nouvelle demande',
      searchPlaceholder: 'Rechercher par titre…',
      filterAll: 'Tous les statuts', filterType: 'Toutes les catégories',
      sortBy: 'Trier par', sortDateDesc: 'Plus récentes', sortDateAsc: 'Plus anciennes',
      sortStatus: 'Statut', sortTitle: 'Titre A–Z',
      results: 'résultat(s)', page: 'Page', of: 'sur', prev: '← Précédent', next: 'Suivant →',
      noResults: 'Aucune demande trouvée',
      noResultsHint: 'Modifiez vos filtres ou créez une nouvelle demande.',
      noResultsHintManager: 'Aucune demande ne correspond à vos critères.',
      createFirst: 'Créer ma première demande',
      unreadMsg: 'non lu(s)', actions: 'Actions',
      view: 'Voir', edit: 'Modifier', delete: 'Supprimer',
      confirmDelete: 'Supprimer cette demande ?', cancelDelete: 'Annuler',
      loading: 'Chargement des demandes…',
    },
    request: {
      detail: 'Détail de la demande', info: 'Informations', description: 'Description',
      history: 'Historique des statuts', conversation: 'Conversation',
      noMessages: 'Aucun message pour le moment. Démarrez la conversation !',
      messagePlaceholder: 'Écrivez votre message...', sendMessage: 'Envoyer',
      createdBy: 'Créé par', createdAt: 'Créé le', updatedAt: 'Mis à jour le',
      status: 'Statut', type: 'Catégorie', edit: 'Modifier',
      manageStatus: 'Gestion du statut',
      setInProgress: 'Mettre en cours', setResolved: 'Marquer résolu', setClosed: 'Fermer',
      closedMessage: 'Cette demande est fermée. La messagerie est désactivée.',
      backToDashboard: 'Tableau de bord', loading: 'Chargement...',
      notFound: 'Demande introuvable', noAccess: "Accès non autorisé",
      request: 'Demande', messageMinLength: 'Minimum 5 caractères',
      statusChanged: 'Statut mis à jour avec succès.',
      youBadge: 'Vous', managerBadge: 'Gestionnaire',
    },
    notifications: {
      title: 'Notifications', subtitle: 'Vos messages et mises à jour récentes',
      markAllRead: 'Tout marquer comme lu', empty: 'Aucune notification',
      emptyHint: 'Vous serez notifié des mises à jour sur vos demandes.',
      openRequest: 'Voir la demande', reply: 'Répondre',
      replyPlaceholder: 'Écrire une réponse...', send: 'Envoyer',
      loading: 'Chargement...', newMessage: 'Nouveau message',
      statusUpdate: 'Mise à jour', seeAll: 'Voir tout',
    },
    status: { SUBMITTED: 'Soumis', IN_PROGRESS: 'En cours', RESOLVED: 'Résolu', CLOSED: 'Fermé' },
    common: {
      loading: 'Chargement...', error: 'Une erreur est survenue.',
      cancel: 'Annuler', save: 'Enregistrer', close: 'Fermer',
      back: 'Retour', next: 'Suivant', edit: 'Modifier',
      search: 'Rechercher', just_now: "À l'instant", ago: 'il y a',
    },
    form: {
      createTitle: 'Créer une nouvelle demande',
      createSubtitle: 'Remplissez le formulaire pour soumettre votre demande',
      editTitle: 'Modifier la demande',
      editSubtitle: 'Mettez à jour les informations de votre demande',
      titleLabel: 'Titre de la demande', titlePlaceholder: 'Ex : Problème de connexion au VPN',
      typeLabel: 'Type de demande', typeDefault: '-- Sélectionnez un type --',
      descriptionLabel: 'Description détaillée',
      descriptionPlaceholder: 'Décrivez votre demande en détail...',
      chars: 'caractères', required: 'requis',
      submitCreate: 'Créer la demande', submitEdit: 'Enregistrer les modifications',
      tipsTitle: 'Conseils pour une bonne demande',
      tip1: 'Choisissez un titre clair et descriptif',
      tip2: 'Sélectionnez le type de demande approprié',
      tip3: 'Décrivez le problème en détail avec les étapes pour le reproduire',
      tip4: 'Mentionnez le navigateur/système utilisé si pertinent',
      tip5: 'Ajoutez des captures d\'écran via les commentaires après création',
      forgotTitle: 'Mot de passe oublié',
      forgotSubtitle: 'Réinitialisez votre mot de passe en quelques étapes',
      stepEmail: 'Email', stepCode: 'Code', stepNewPwd: 'Nouveau mot de passe',
      sendCode: 'Envoyer le code', verifyCode: 'Vérifier le code',
      newPasswordLabel: 'Nouveau mot de passe', confirmPasswordLabel: 'Confirmer le mot de passe',
      resetPassword: 'Réinitialiser',
      codeInfo: 'Un code à 6 chiffres a été envoyé à', codeValid: 'Ce code est valide 15 minutes.',
      leftForgotTitle: 'Récupérez l\'accès à votre compte',
      leftForgotSubtitle: 'En 3 étapes simples et sécurisées.',
      leftForgotPoint1: 'Entrez votre adresse email universitaire',
      leftForgotPoint2: 'Vérifiez le code reçu dans votre boîte mail',
      leftForgotPoint3: 'Choisissez votre nouveau mot de passe',
      loadingRequest: 'Chargement de la demande...', notEditable: 'Modification impossible.',
    },
    footer: {
      rights: '© 2026 UQO Requests — Projet INF1743',
      gatineau: 'Campus Gatineau', saintJerome: 'Campus Saint-Jérôme',
    },
  },
  en: {
    appName: 'UQO Requests',
    appTagline: 'University Request Management Platform',
    nav: {
      dashboard: 'Dashboard', newRequest: 'New Request',
      notifications: 'Notifications', myRequests: 'My Requests',
      allRequests: 'All Requests', logout: 'Sign Out',
      login: 'Sign In', register: 'Sign Up', home: 'Home',
    },
    home: {
      heroTitle: 'Manage your university requests',
      heroSubtitle: 'A modern, secure and intuitive platform to submit, track and resolve your administrative requests — all from one centralized space.',
      heroCtaPrimary: 'Create a request', heroCtaSecondary: 'Sign In',
      heroCta: 'Go to dashboard',
      stat1: 'Requests processed', stat2: 'Avg. response', stat3: 'Resolution rate',
      stat1Val: '1,200+', stat2Val: '24h', stat3Val: '98%',
      feature1Title: 'Real-time tracking', feature1Desc: 'Track the progress of your requests at every step of the process.',
      feature2Title: 'Direct communication', feature2Desc: 'Exchange directly with managers via the built-in messaging system.',
      feature3Title: 'Instant notifications', feature3Desc: 'Be alerted immediately when your requests are updated.',
      feature4Title: 'Enhanced security', feature4Desc: 'Two-factor authentication to protect your account.',
      welcomeBack: 'Welcome back,',
      ctaTitle: 'Ready to get started?',
      ctaSubtitle: 'Join UQO students already using the platform.',
      ctaBtn: 'Create my account',
      howItWorks: 'How it works',
      step1Title: 'Submit', step1Desc: 'Fill out the request form in a few clicks.',
      step2Title: 'Track', step2Desc: 'Check the status and updates of your request.',
      step3Title: 'Communicate', step3Desc: 'Exchange with your manager until resolution.',
    },
    auth: {
      loginTitle: 'Sign In', loginSubtitle: 'Access your personal space',
      registerTitle: 'Create Account', registerSubtitle: 'Join the UQO community',
      emailLabel: 'Email address', emailPlaceholder: 'jean.dupont@uqo.ca',
      passwordLabel: 'Password', passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirm password',
      fullNameLabel: 'Full name', fullNamePlaceholder: 'Jean Dupont',
      codeLabel: 'Verification code', codePlaceholder: '123456',
      codeInfo: 'A 6-digit code has been sent to your email address. This code is valid for 15 minutes.',
      next: 'Continue', back: 'Back', submit: 'Sign In',
      submitRegister: 'Sign Up', verify: 'Verify code',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?", hasAccount: 'Already have an account?',
      signUp: 'Sign Up', signIn: 'Sign In',
      passwordHint: 'Minimum 8 characters, 1 uppercase, 1 number',
      show: 'Show', hide: 'Hide',
      step1: 'Email', step2: 'Password', step3: 'Verification',
      leftTitle: 'The reference platform for UQO students',
      leftSubtitle: 'Simple, fast and secure.',
      leftPoint1: 'Submit your requests in a few clicks',
      leftPoint2: 'Track their progress in real time',
      leftPoint3: 'Communicate directly with managers',
    },
    dashboard: {
      title: 'Dashboard', managerTitle: 'Request Management',
      subtitle: "Here's what's happening on your space",
      managerSubtitle: 'Overview of all requests',
      newRequest: 'New Request',
      total: 'Total', submitted: 'Submitted', inProgress: 'In Progress',
      resolved: 'Resolved', closed: 'Closed', all: 'All',
      loading: 'Loading…', error: 'Unable to load data.',
      colTitle: 'Title', colCategory: 'Category', colStatus: 'Status',
      colDate: 'Date', colCreatedBy: 'Created by',
      statusChart: 'Status breakdown',
      recentRequests: 'Recent requests', recentActivity: 'Recent activity',
      recentNotifications: 'Recent notifications',
      viewAll: 'View all', noActivity: 'No recent activity',
      noRecentRequests: 'No requests yet',
      goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
    },
    myRequests: {
      title: 'My Requests', managerTitle: 'All Requests',
      subtitle: 'Manage and track your requests', managerSubtitle: 'Supervise and process all requests',
      newRequest: 'New Request',
      searchPlaceholder: 'Search by title…',
      filterAll: 'All statuses', filterType: 'All categories',
      sortBy: 'Sort by', sortDateDesc: 'Newest', sortDateAsc: 'Oldest',
      sortStatus: 'Status', sortTitle: 'Title A–Z',
      results: 'result(s)', page: 'Page', of: 'of', prev: '← Previous', next: 'Next →',
      noResults: 'No requests found',
      noResultsHint: 'Adjust your filters or create a new request.',
      noResultsHintManager: 'No requests match your criteria.',
      createFirst: 'Create my first request',
      unreadMsg: 'unread', actions: 'Actions',
      view: 'View', edit: 'Edit', delete: 'Delete',
      confirmDelete: 'Delete this request?', cancelDelete: 'Cancel',
      loading: 'Loading requests…',
    },
    request: {
      detail: 'Request Detail', info: 'Information', description: 'Description',
      history: 'Status History', conversation: 'Conversation',
      noMessages: 'No messages yet. Start the conversation!',
      messagePlaceholder: 'Write your message...', sendMessage: 'Send',
      createdBy: 'Created by', createdAt: 'Created', updatedAt: 'Updated',
      status: 'Status', type: 'Category', edit: 'Edit',
      manageStatus: 'Manage Status',
      setInProgress: 'Set In Progress', setResolved: 'Mark Resolved', setClosed: 'Close Request',
      closedMessage: 'This request is closed. Messaging is disabled.',
      backToDashboard: 'Dashboard', loading: 'Loading...',
      notFound: 'Request not found', noAccess: 'Access denied',
      request: 'Request', messageMinLength: 'Minimum 5 characters',
      statusChanged: 'Status updated successfully.',
      youBadge: 'You', managerBadge: 'Manager',
    },
    notifications: {
      title: 'Notifications', subtitle: 'Your recent messages and updates',
      markAllRead: 'Mark all as read', empty: 'No notifications',
      emptyHint: 'You will be notified of updates on your requests.',
      openRequest: 'View request', reply: 'Reply',
      replyPlaceholder: 'Write a reply...', send: 'Send',
      loading: 'Loading...', newMessage: 'New message',
      statusUpdate: 'Status update', seeAll: 'See all',
    },
    status: { SUBMITTED: 'Submitted', IN_PROGRESS: 'In Progress', RESOLVED: 'Resolved', CLOSED: 'Closed' },
    common: {
      loading: 'Loading...', error: 'An error occurred.',
      cancel: 'Cancel', save: 'Save', close: 'Close',
      back: 'Back', next: 'Next', edit: 'Edit',
      search: 'Search', just_now: 'Just now', ago: 'ago',
    },
    form: {
      createTitle: 'Create a new request',
      createSubtitle: 'Fill out the form to submit your request',
      editTitle: 'Edit request',
      editSubtitle: 'Update the information for your request',
      titleLabel: 'Request title', titlePlaceholder: 'e.g. VPN connection issue',
      typeLabel: 'Request type', typeDefault: '-- Select a type --',
      descriptionLabel: 'Detailed description',
      descriptionPlaceholder: 'Describe your request in detail...',
      chars: 'characters', required: 'required',
      submitCreate: 'Create request', submitEdit: 'Save changes',
      tipsTitle: 'Tips for a good request',
      tip1: 'Choose a clear and descriptive title',
      tip2: 'Select the appropriate request type',
      tip3: 'Describe the issue in detail with steps to reproduce',
      tip4: 'Mention the browser/system used if relevant',
      tip5: 'Add screenshots via comments after creation',
      forgotTitle: 'Forgot password',
      forgotSubtitle: 'Reset your password in a few steps',
      stepEmail: 'Email', stepCode: 'Code', stepNewPwd: 'New password',
      sendCode: 'Send code', verifyCode: 'Verify code',
      newPasswordLabel: 'New password', confirmPasswordLabel: 'Confirm password',
      resetPassword: 'Reset password',
      codeInfo: 'A 6-digit code has been sent to', codeValid: 'This code is valid for 15 minutes.',
      leftForgotTitle: 'Regain access to your account',
      leftForgotSubtitle: 'In 3 simple and secure steps.',
      leftForgotPoint1: 'Enter your university email address',
      leftForgotPoint2: 'Check the code received in your inbox',
      leftForgotPoint3: 'Choose your new password',
      loadingRequest: 'Loading request...', notEditable: 'Cannot edit this request.',
    },
    footer: {
      rights: '© 2026 UQO Requests — INF1743 Project',
      gatineau: 'Gatineau Campus', saintJerome: 'Saint-Jérôme Campus',
    },
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('uqo_lang') || 'fr')

  const toggleLang = () => {
    const next = lang === 'fr' ? 'en' : 'fr'
    setLang(next)
    localStorage.setItem('uqo_lang', next)
  }

  const t = useMemo(() => translations[lang], [lang])

  const value = useMemo(() => ({ lang, toggleLang, t, isFr: lang === 'fr' }), [lang, t])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang() must be used inside <LanguageProvider>')
  return ctx
}
